// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYQtMP-nWrF8P9sNEoOxcVqbgXT7hsUH4',
    appId: '1:1096653819628:web:b721e014b0441f2f4a9fc9',
    messagingSenderId: '1096653819628',
    projectId: 'fasum-ee6c4',
    authDomain: 'fasum-ee6c4.firebaseapp.com',
    storageBucket: 'fasum-ee6c4.appspot.com',
    measurementId: 'G-4DRP1JZHD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU3GJNEel_GDKqGs2A2CTQIc6nseSvL8U',
    appId: '1:1096653819628:android:7b65f6f3231fccde4a9fc9',
    messagingSenderId: '1096653819628',
    projectId: 'fasum-ee6c4',
    storageBucket: 'fasum-ee6c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBudqvspoT-SGrRy1YTeH_BPBHWwIf56Oo',
    appId: '1:1096653819628:ios:cef60e99803792dd4a9fc9',
    messagingSenderId: '1096653819628',
    projectId: 'fasum-ee6c4',
    storageBucket: 'fasum-ee6c4.appspot.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBudqvspoT-SGrRy1YTeH_BPBHWwIf56Oo',
    appId: '1:1096653819628:ios:1b2a490f729797914a9fc9',
    messagingSenderId: '1096653819628',
    projectId: 'fasum-ee6c4',
    storageBucket: 'fasum-ee6c4.appspot.com',
    iosBundleId: 'com.example.fasum.RunnerTests',
  );
}
